#!/usr/bin/env bash

install_packages="$1"

if [ "$install_packages" == 'install' ];
    then ./packages $2
fi

# config files
mkdir -p ~/.config

# copy config
ln -f -s $PWD/.config/neofetch ~/.config
ln -f -s $PWD/.config/alacritty ~/.config
ln -f -s $PWD/.config/starship.toml ~/.config/starship.toml
ln -f -s $PWD/.zshrc ~/.zshrc
ln -f -s $PWD/aliases ~/aliases
ln -f -s $PWD/.tmux.conf ~/.tmux.conf

tmux source ~/.tmux.conf 
