#!/usr/bin/env bash

# First argument is the operating system
os="$1"

# Install packages
if [ "$os" == 'mac' ];
then 
    arch -arm64 brew install zsh zsh-completions starship alacritty neofetch nano cmatrix htop ranger tmux
    chsh -s /bin/zsh

elif [ "$os" == 'ubuntu' ];
then
    sudo apt install alacritty neofetch zsh zsh-completions tmux starship nano cmatrix htop ranger tmux
    chsh -s $(which zsh) 
fi

# config files
mkdir -p ~/.config

# Copy config
ln -f -s $PWD/.config/neofetch ~/.config
ln -f -s $PWD/.config/alacritty ~/.config
ln -f -s $PWD/.config/starship.toml ~/.config/starship.toml
ln -f -s $PWD/.zshrc ~/.zshrc
