#!/usr/bin/env bash

# First argument is the operating system
os="$1"

packages_arr=(
	"zsh"
	"zsh-completions" 
	"starship"
	"alacritty"
	"neofetch" 
	"nano" 
	"cmatrix" 
	"htop" 
	"ranger" 
	"tmux"
	"postgresql@14"
	"docker"
	"visual-studio-code"
	"neovim"
	"btop"
	"font-space-mono-nerd-font"
)
packages_str="${packages_arr[*]}"

# Install packages
if [ "$os" == 'mac' ];
then
    arch -arm64 brew install ${packages_str}
    chsh -s /bin/zsh

elif [ "$os" == 'ubuntu' ];
then
    sudo apt install ${packages_str}
    chsh -s $(which zsh)
else
    echo "OS must be either 'mac' or 'ubuntu'"
fi

