#!/usr/bin/env bash

# First argument is the operating system
os="$1"

# Install packages
if [ "$os" == 'mac' ];
then
    arch -arm64 brew install zsh zsh-completions starship alacritty neofetch nano cmatrix htop ranger tmux
    chsh -s /bin/zsh

elif [ "$os" == 'ubuntu' ];
then
    sudo apt install alacritty neofetch zsh zsh-completions tmux starship nano cmatrix htop ranger tmux
    chsh -s $(which zsh)
fi

