#!/usr/bin/env bash

install_packages="$1"

if [ "$install_packages" == '--install' ];
then
    if [ "$(uname)" == "Darwin" ]; 
        then ./packages/mac
    elif [ "$(uname)" == "Linux" ];
        then ./packages/ubuntu
    fi
fi

# config files
mkdir -p ~/.config

# symlimk Linux specific config
if [ "$(uname)" == "Linux" ];
then 
  ln -f -s "$PWD"/.config/polybar ~/.config
  ln -f -s "$PWD"/.config/i3 ~/.config
  ln -f -s "$PWD"/.config/rofi ~/.config
  ln -f -s "$PWD"/.config/picom ~/.config
fi 

# symlimk OS-agnostic config
ln -f -s "$PWD"/.config/neofetch ~/.config
ln -f -s "$PWD"/.config/alacritty ~/.config
ln -f -s "$PWD"/.config/nvim ~/.config
ln -f -s "$PWD"/.config/starship.toml ~/.config/starship.toml
ln -f -s "$PWD"/.zshrc ~/.zshrc
ln -f -s "$PWD"/aliases ~/aliases
ln -f -s "$PWD"/.tmux.conf ~/.tmux.conf
ln -f -s "$PWD"/wallpapers ~


# tmux && tmux source ~/.tmux.conf 
