#!/usr/bin/env bash

install_packages="$1"

if [ "$install_packages" == '--install' ];
then
    if [ "$(uname)" == "Darwin" ]; 
        then ./packages/mac
    elif [ "$(uname)" == "Linux" ];
        then ./packages/ubuntu
    fi
fi

# config files
mkdir -p ~/.config

# symlimk OS-specific config
if [ "$(uname)" == "Darwin" ];
then
  # VSCode settings
  ln -f -s "$PWD"/.config/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
elif [ "$(uname)" == "Linux" ];
then 
  ln -f -s "$PWD"/.config/polybar ~/.config
  ln -f -s "$PWD"/.config/i3 ~/.config
  ln -f -s "$PWD"/.config/rofi ~/.config
  ln -f -s "$PWD"/.config/picom ~/.config
  ln -f -s "$PWD"/.config/vscode/settings.json ~/.config/Code/User/settings.json
fi 

# symlimk OS-agnostic config
ln -f -s "$PWD"/.config/neofetch ~/.config
ln -f -s "$PWD"/.config/alacritty ~/.config
ln -f -s "$PWD"/.config/nvim ~/.config
ln -f -s "$PWD"/.config/starship.toml ~/.config/starship.toml
ln -f -s "$PWD"/.zshrc ~/.zshrc
ln -f -s "$PWD"/.aliases ~/.aliases
ln -f -s "$PWD"/.functions ~/.functions
ln -f -s "$PWD"/.config/.tmux.conf ~/.tmux.conf
ln -f -s "$PWD"/.config/.gitconfig ~/.gitconfig
ln -f -s "$PWD"/wallpapers ~


tmux source ~/.tmux.conf 
